import type { BillGroup, BillPageSnapshot } from "@/lib/types/bill";

const mockGroups: BillGroup[] = [
  {
    id: "2026-04-23",
    label: "今天",
    subtitle: "4月23日",
    expenseTotal: 522.45,
    incomeTotal: 3100,
    currency: "AED",
    items: [
      {
        id: "bill-1",
        userId: "user-1",
        accountId: "acc-adcb",
        categoryId: "cat-shopping",
        type: "expense",
        title: "Apple Pay 自动记账",
        note: null,
        amount: -89.9,
        currency: "AED",
        occurredAt: "2026-04-23T18:45:00.000Z",
        merchantName: "Apple Pay",
        accountName: "ADCB **** 1234",
        iconKey: "apple",
        tagLabel: "购物",
        tagTone: "expense",
      },
      {
        id: "bill-2",
        userId: "user-1",
        accountId: "acc-adcb",
        categoryId: "cat-subscription",
        type: "expense",
        title: "Ai",
        note: "订阅",
        amount: -19.99,
        currency: "AED",
        occurredAt: "2026-04-23T16:32:00.000Z",
        merchantName: "OpenAI",
        accountName: "ADCB **** 1234",
        iconKey: "ai",
        tagLabel: "订阅",
        tagTone: "income",
      },
      {
        id: "bill-3",
        userId: "user-1",
        accountId: "acc-okx",
        categoryId: "cat-wealth",
        type: "wealth",
        title: "OKX 理财收益",
        note: null,
        amount: 1200,
        currency: "USDT",
        occurredAt: "2026-04-23T09:15:00.000Z",
        merchantName: "OKX",
        accountName: "OKX 资金账户",
        iconKey: "okx",
        tagLabel: "理财",
        tagTone: "wealth",
      },
      {
        id: "bill-4",
        userId: "user-1",
        accountId: "acc-adcb",
        categoryId: "cat-transfer",
        type: "transfer",
        title: "转账给张三",
        note: null,
        amount: -500,
        currency: "AED",
        occurredAt: "2026-04-23T08:20:00.000Z",
        merchantName: null,
        accountName: "ADCB **** 1234",
        iconKey: "bank",
        tagLabel: "转账",
        tagTone: "transfer",
      },
    ],
  },
  {
    id: "2026-04-22",
    label: "昨天",
    subtitle: "4月22日",
    expenseTotal: 1245.6,
    incomeTotal: 6500,
    currency: "AED",
    items: [
      {
        id: "bill-5",
        userId: "user-1",
        accountId: "acc-huobi",
        categoryId: "cat-wealth",
        type: "wealth",
        title: "火币 理财收益",
        note: null,
        amount: 2500,
        currency: "USDT",
        occurredAt: "2026-04-22T21:35:00.000Z",
        merchantName: "Huobi",
        accountName: "火币 资金账户",
        iconKey: "fire",
        tagLabel: "理财",
        tagTone: "wealth",
      },
      {
        id: "bill-6",
        userId: "user-1",
        accountId: "acc-bitget",
        categoryId: "cat-wealth",
        type: "wealth",
        title: "Bitget 理财收益",
        note: null,
        amount: 4000,
        currency: "USDT",
        occurredAt: "2026-04-22T14:10:00.000Z",
        merchantName: "Bitget",
        accountName: "Bitget 资金账户",
        iconKey: "bitget",
        tagLabel: "理财",
        tagTone: "wealth",
      },
      {
        id: "bill-7",
        userId: "user-1",
        accountId: "acc-adcb",
        categoryId: "cat-shopping",
        type: "expense",
        title: "Noon",
        note: null,
        amount: -245.6,
        currency: "AED",
        occurredAt: "2026-04-22T11:05:00.000Z",
        merchantName: "Noon",
        accountName: "ADCB **** 1234",
        iconKey: "shop",
        tagLabel: "购物",
        tagTone: "expense",
      },
    ],
  },
  {
    id: "2026-04-21",
    label: "4月21日",
    subtitle: "星期一",
    expenseTotal: 1862.36,
    incomeTotal: 2300,
    currency: "AED",
    items: [
      {
        id: "bill-8",
        userId: "user-1",
        accountId: "acc-adcb",
        categoryId: "cat-shopping",
        type: "expense",
        title: "Amazon.ae",
        note: null,
        amount: -112.36,
        currency: "AED",
        occurredAt: "2026-04-21T20:22:00.000Z",
        merchantName: "Amazon",
        accountName: "ADCB **** 1234",
        iconKey: "amazon",
        tagLabel: "购物",
        tagTone: "expense",
      },
      {
        id: "bill-9",
        userId: "user-1",
        accountId: "acc-adcb",
        categoryId: "cat-transport",
        type: "expense",
        title: "Careem",
        note: null,
        amount: -35,
        currency: "AED",
        occurredAt: "2026-04-21T18:08:00.000Z",
        merchantName: "Careem",
        accountName: "ADCB **** 1234",
        iconKey: "card",
        tagLabel: "交通",
        tagTone: "income",
      },
      {
        id: "bill-10",
        userId: "user-1",
        accountId: "acc-okx",
        categoryId: "cat-wealth",
        type: "wealth",
        title: "OKX 理财收益",
        note: null,
        amount: 2300,
        currency: "USDT",
        occurredAt: "2026-04-21T10:30:00.000Z",
        merchantName: "OKX",
        accountName: "OKX 资金账户",
        iconKey: "okx",
        tagLabel: "理财",
        tagTone: "wealth",
      },
    ],
  },
];

export async function getBillPageSnapshot(): Promise<BillPageSnapshot> {
  return {
    monthLabel: "2026年4月",
    summary: {
      expenseAmount: 7109.71,
      expenseTrend: 13.2,
      incomeAmount: 47556.16,
      incomeTrend: 18.7,
      currency: "AED",
    },
    groups: mockGroups,
  };
}
